### ISSUE TITLE
April 04

### ISSUE THREAD

**Issue by SevlaMare** [ferbaco86/Newsweek-clone#2]

**Comment by SevlaMare** [comment]
The margins of first grid can be improved on 768px breakpoint (default size for android tablet and ipad)

**Comment by FrancoRosa** [comment]
Awesome project man, specially for the scrolling feature.
Only one thing (The weather icon).
**Mine:**
![image](https://user-images.githubusercontent.com/5665734/78795683-e436f780-797a-11ea-8fce-fd38dfd3bee9.png)
**Yours:**
![image](https://user-images.githubusercontent.com/5665734/78795894-2a8c5680-797b-11ea-8675-dcd8bf89f5da.png)
